version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - presto

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1U8f)-W33T-I
      POSTGRES_DB: frodo
    volumes:
      - ./src:/app/src
      - /app/node_modules

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1U8f)-W33T-I
      POSTGRES_DB: frodo
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  presto:
    image: trinodb/trino:latest
    ports:
      - "8888:8080"
    environment:
      - DISCOVERY_SERVICE=none
    volumes:
      - ./resources/presto:/etc/config
      - presto-data:/var/lib/presto/data

volumes:
    postgres-data:
    presto-data:
