name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: registry.veriface.online
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: registry.veriface.online/veriface.online:latest

    - name: Deploy new version
      run: |
        cd /home/deployer/infra
        docker-compose pull api
        docker-compose up -d --no-deps api